# Generated by Django 5.1.4 on 2025-01-15 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cateegory',
            new_name='category',
        ),
    ]
